s = set()
m = input("Enter the number: ")
s.add(int(m))
m = input("Enter the number: ")
s.add(int(m))
m = input("Enter the number: ")
s.add(int(m))
m = input("Enter the number: ")
s.add(int(m))
m = input("Enter the number: ")
s.add(int(m))
m = input("Enter the number: ")
s.add(int(m))
m = input("Enter the number: ")
s.add(int(m))
m = input("Enter the number: ")
s.add(int(m))
print(s)
